Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-11"
    config.vm.network "private_network", ip: "192.168.10.100"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    config.vm.provision "shell", inline: <<-SHELL
      if [[ ! -f "/usr/bin/puppet" ]]; then
        apt-get update
        apt-get install -y puppet
      fi
    SHELL

    config.vm.provision "puppet" do |puppet|
      puppet.module_path = "modules"
      puppet.facter = {
        "private_network_ip" => "192.168.10.100"
      }
    end
end
